type t = ..
(** The type of lexer and parser tokens. *)

(** All tokens produced by the lexer. *)
type t +=
  | Eq  (** Equality operator [=]. *)
  | Neq  (** Inequality operator [!=]. *)
  | LogicalOr  (** Logical OR [||]. *)
  | LogicalAnd  (** Logical AND [&&]. *)
  | Pow  (** Exponentiation operator [**] or similar. *)
  | Dec  (** Decrement operator [--]. *)
  | Inc  (** Increment operator [++]. *)
  | Impiles  (** Implication operator [->] or [=>]. *)
  | MapsTo  (** Mapping operator [=>] or similar. *)
  | PlusAssign  (** Compound assignment [+=]. *)
  | MinusAssign  (** Compound assignment [-=]. *)
  | StarAssign  (** Compound assignment [*=]. *)
  | SlashAssign  (** Compound assignment [/=]. *)
  | Plus  (** Addition [+]. *)
  | Minus  (** Subtraction [-]. *)
  | Star  (** Multiplication [*]. *)
  | Slash  (** Division [/]. *)
  | Mod  (** Remainder [%]. *)
  | Carot  (** Bitwise XOR [^]. *)
  | ArrConcat  (** Array concatenation operator. *)
  | Assign  (** Assignment operator [=]. *)
  | Greater  (** Greater-than [>]. *)
  | Less  (** Less-than [<]. *)
  | Not  (** Logical NOT [!]. *)
  | Pipe  (** Pipe operator [|]. *)
  | DeRef  (** Dereference operator [*] or similar. *)
  | Question  (** Question mark [?], often used in ternary or option syntax. *)
  | Binary of int  (** Binary literal. *)
  | BitWiseAND  (** Bitwise AND [&]. *)
  | BitWiseOR  (** Bitwise OR [|]. *)
  | BitWiseXOR  (** Bitwise XOR [^]. *)
  | BitWiseNOT  (** Bitwise NOT [~]. *)
  | LeftShift  (** Left shift [<<]. *)
  | RightShift  (** Right shift [>>]. *)
  | BitWiseANDAssign  (** [&=] assignment. *)
  | BitWiseORAssign  (** [|=] assignment. *)
  | BitWiseXORAssign  (** [^=] assignment. *)
  | LeftShiftAssign  (** [<<=] assignment. *)
  | RightShiftAssign  (** [>>=] assignment. *)
  | Pipeline  (** Pipeline operator [|>]. *)
  | Range  (** Range operator [..]. *)
  | LParen  (** Left parenthesis [(]. *)
  | RParen  (** Right parenthesis [)]. *)
  | LBracket  (** Left bracket [\[]. *)
  | RBracket  (** Right bracket [\]]. *)
  | LBrace  (** Left brace [{]. *)
  | RBrace  (** Right brace [}]. *)
  | Dot  (** Dot operator [.]. *)
  | Colon  (** Colon [:]. *)
  | Semi  (** Semicolon [;]. *)
  | Comma  (** Comma [,]. *)
  | UnderScore  (** Underscore [_]. *)
  | Function  (** [fun] or [function] keyword. *)
  | Recursive  (** [rec] keyword for recursive definitions. *)
  | If  (** [if] keyword. *)
  | Then  (** [then] keyword. *)
  | Else  (** [else] keyword. *)
  | Let  (** [let] keyword. *)
  | Match  (** [match] keyword. *)
  | With  (** [with] keyword. *)
  | Return  (** [return] keyword. *)
  | Use  (** [use] keyword. *)
  | Module  (** [module] keyword. *)
  | Enum  (** [enum] keyword. *)
  | Ref  (** [ref] keyword. *)
  | IntType  (** [int] type. *)
  | FloatType  (** [float] type. *)
  | StringType  (** [string] type. *)
  | ByteType  (** [byte] type. *)
  | BoolType  (** [bool] type. *)
  | UnitType  (** [unit] type. *)
  | True  (** Boolean literal [true]. *)
  | False  (** Boolean literal [false]. *)
  | Ident of string  (** Identifier. *)
  | Int of Bigint.t  (** Integer literal. *)
  | Float of float  (** Floating-point literal. *)
  | String of string  (** String literal. *)
  | Byte of char  (** Byte/character literal. *)
  | Bool of bool  (** Boolean literal. *)
  | Unit of unit  (** Unit literal [()]. *)
  | Tuple of t list  (** Tuple literal. *)
  | EOF  (** End-of-file marker. *)
