(test
 (name lexer_test)
 (libraries calyxium_stdlib calyxium_lib))

(test
 (name gc_test)
 (libraries calyxium_stdlib calyxium_vm))

(rule
 (alias cx_tests)
 (deps
  %{bin:calyxium}
  (glob_files *.cx))
 (action
  (run
   bash
   -c
   "set -e; for f in *.cx; do calyxium \"$f\" > /dev/null; echo Passed: $f; done")))

(alias
 (name runtest)
 (deps
  (alias cx_tests)))
