val reset : string
val bold : string
val dim : string
val italic : string
val underline : string
val blink : string
val reverse : string
val black : string
val red : string
val green : string
val yellow : string
val blue : string
val magenta : string
val cyan : string
val white : string
val bright_red : string
val bright_green : string
val bright_yellow : string
val bright_blue : string
val bright_magenta : string
val bright_cyan : string
