(library
 (name calyxiumlib)
 (public_name calyxium.lib)
 (modules
  ast
  token
  lexer
  parser
  typechecker
  opcode
  bytecode
  bytegen
  vm
  gc
  color
  error
  help
  version
  uint32
  uint64
  init
  formatter
  pretty
  toml_config)
 (foreign_stubs
  (language c)
  (names uint32 uint64))
 (libraries calyxium_stdlib unix)
 (preprocess
  (pps ppx_deriving.show)))

(ocamllex lexer)

(ocamlyacc parser)
