(library
 (name calyxiumlib)
 (public_name calyxium.lib)
 (modules
  ast
  lexer
  parser
  token
  version
  typechecker
  error
  help
  color
  bytecode
  opcode
  vm
  gc)
 (libraries unix ppx_deriving.show)
 (preprocess
  (pps ppx_deriving.show)))

(ocamllex lexer)

(menhir
 (modules parser)
 (infer true))

(documentation)
