(library
 (name calyxiumlib)
 (public_name calyxium.lib)
 (modules
  ast
  token
  lexer
  parser
  typechecker
  opcode
  bytecode
  bytegen
  vm
  gc
  color
  error
  help
  version
  uint32)
 (foreign_stubs
  (language c)
  (names uint32))
 (libraries unix ppx_deriving.show)
 (preprocess
  (pps ppx_deriving.show)))

(ocamllex lexer)

(ocamlyacc parser)

(documentation)
