open Calyxium_parser

type opcode = ..
(** Virtual machine instructions (opcodes). *)

(** Opcode variants representing operations in the Calyxium VM. *)
type opcode +=
  | LOAD_INT of Bigint.t  (** Load an integer constant. *)
  | LOAD_FLOAT of float  (** Load a float constant. *)
  | LOAD_STRING of string  (** Load a string constant. *)
  | LOAD_BYTE of char  (** Load a byte/char constant. *)
  | LOAD_BOOL of bool  (** Load a boolean constant. *)
  | LOAD_UNIT of unit  (** Load the unit value. *)
  | LOAD_TUPLE of int  (** Load a tuple of given size. *)
  | LOAD_ARRAY of int  (** Load an array of given size. *)
  | LOAD_VAR of string  (** Load the value of a variable. *)
  | STORE_VAR of string  (** Store the top of stack into a variable. *)
  | FUNCTION of string  (** Declare a function with a name. *)
  | LOAD_VAR_REF of string  (** Load a reference to a variable. *)
  | JUMP of int  (** Unconditional jump by instruction offset. *)
  | JUMP_IF_FALSE of int  (** Jump if top-of-stack is false. *)
  | CALL of string  (** Call a named function. *)
  | TAIL_CALL of string  (** Tail-call optimization. *)
  | LOAD_INDEX  (** Load an element from array or tuple. *)
  | PLUS  (** Addition. *)
  | MINUS  (** Subtraction. *)
  | STAR  (** Multiplication. *)
  | SLASH  (** Division. *)
  | MOD  (** Modulus. *)
  | POW  (** Exponentiation. *)
  | CONCAT  (** Concatenate arrays or strings. *)
  | AND  (** Logical AND. *)
  | OR  (** Logical OR. *)
  | GREATER  (** Greater-than comparison. *)
  | LESS  (** Less-than comparison. *)
  | EQUAL  (** Equality comparison. *)
  | GREATER_EQUAL  (** Greater-or-equal comparison. *)
  | LESS_EQUAL  (** Less-or-equal comparison. *)
  | NOT_EQUAL  (** Inequality comparison. *)
  | RETURN  (** Return from function. *)
  | PRINT  (** Print top-of-stack. *)
  | NOT  (** Logical NOT. *)
  | INC  (** Increment top-of-stack. *)
  | DEC  (** Decrement top-of-stack. *)
  | DUP  (** Duplicate top-of-stack. *)
  | POP  (** Pop top-of-stack. *)
  | INPUT  (** Read input. *)
  | NEG  (** Negate top-of-stack numeric value. *)
  | FLOAT  (** Convert top-of-stack to float. *)
  | INT  (** Convert top-of-stack to int. *)
  | STRING  (** Convert top-of-stack to string. *)
  | BYTES  (** Convert top-of-stack to bytes. *)
  | BYTE  (** Convert top-of-stack to byte/char. *)
  | PLUSASSIGN  (** Add and assign. *)
  | MINUSASSIGN  (** Subtract and assign. *)
  | STARASSIGN  (** Multiply and assign. *)
  | SLASHASSIGN  (** Divide and assign. *)
  | LENGTH  (** Get length of array/string. *)
  | BITWISEAND  (** Bitwise AND. *)
  | BITWISEOR  (** Bitwise OR. *)
  | BITWISEXOR  (** Bitwise XOR. *)
  | BITWISENOT  (** Bitwise NOT. *)
  | LEFTSHIFT  (** Left shift bits. *)
  | RIGHTSHIFT  (** Right shift bits. *)
  | BITWISEANDASSIGN  (** Bitwise AND and assign. *)
  | BITWISEORASSIGN  (** Bitwise OR and assign. *)
  | BITWISEXORASSIGN  (** Bitwise XOR and assign. *)
  | LEFTSHIFTASSIGN  (** Left shift and assign. *)
  | RIGHTSHIFTASSIGN  (** Right shift and assign. *)
  | ASSERT  (** Runtime assertion. *)
  | LOAD_MODULE of string  (** Load a module by name. *)
  | LOAD_FIELD of string  (** Load a field from a module or object. *)
  | CLOSURE of string  (** Create a closure with a name. *)
  | PANIC  (** Trigger a runtime panic/error. *)
  | MAKE_RANGE  (** Create a range object. *)
  | ARRAYCONCAT  (** Concatenate two arrays. *)
  | SLICE  (** Slice an array or string. *)
  | TYPE  (** Push the type of a value. *)
  | CALL_CLOSURE of int  (** Call a closure with N arguments. *)
  | TAIL  (** Tail-call marker. *)
  | HEAD  (** Get first element of array/tuple. *)
  | REVERSE  (** Reverse an array or tuple. *)
  | FST  (** Get first element of a tuple. *)
  | SND  (** Get second element of a tuple. *)
