module Math = struct
  external c_sin : float -> float = "caml_sin"
  external c_cos : float -> float = "caml_cos"
  external c_tan : float -> float = "caml_tan"
  external c_asin : float -> float = "caml_asin"
  external c_acos : float -> float = "caml_acos"
  external c_atan : float -> float = "caml_atan"
  external c_atan2 : float -> float = "caml_atan2"
  external c_exp : float -> float = "caml_exp"
  external c_log : float -> float = "caml_log"
  external c_log10 : float -> float = "caml_log10"
  external c_pow : float -> float = "caml_pow"
  external c_sqrt : float -> float = "caml_sqrt"
  external c_cbrt : float -> float = "caml_cbrt"
  external c_sinh : float -> float = "caml_sinh"
  external c_cosh : float -> float = "caml_cosh"
  external c_tanh : float -> float = "caml_tanh"

  let pi = 3.141592653589
  let e = 2.71828
  let tau = 2. *. pi
  let infinity = infinity
  let nan = nan
  let neg_infinity = neg_infinity
  let sin = c_sin
  let cos = c_cos
  let tan = c_tan
  let asin = c_asin
  let acos = c_acos
  let atan = c_atan
  let atan2 = c_atan2
  let exp = c_exp
  let log = c_log
  let log10 = c_log10
  let pow = c_pow
  let sqrt = c_sqrt
  let cbrt = c_cbrt
  let sinh = c_sinh
  let cosh = c_cosh
  let tanh = c_tanh
  let clamp lo hi x = if x < lo then lo else if x > hi then hi else x
end
